name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (including binary)
      run: cargo build --all-features --bin qrgen --verbose
    - name: Run Clippy
      run: cargo clippy --all-features --bin qrgen
    - name: Run tests
      run: cargo test --verbose
